const fs=require('fs');const path=require('path');
function send(res,status,data,cache='s-maxage=3600, stale-while-revalidate=86400'){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control',cache);res.end(JSON.stringify(data))}
async function getJSON(url,ms=8000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'WebsiteOfBabel/11.0'}});if(!r.ok)throw new Error(`${r.status}`);return await r.json()}finally{clearTimeout(t)}}
async function getText(url,ms=8000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'WebsiteOfBabel/11.0'}});if(!r.ok)throw new Error(`${r.status}`);return await r.text()}finally{clearTimeout(t)}}
const fallbackProgramming=['JavaScript','TypeScript','Python','C','C++','C#','Java','Go','Rust','Swift','Kotlin','PHP','Ruby','Lua','R','Julia','Haskell','Scala','Elixir','Erlang','Clojure','F#','Dart','Perl','Shell','PowerShell','SQL','Solidity','Assembly','Fortran','COBOL','Pascal','Objective-C','Zig','Nim','Crystal','OCaml','Scheme','Common Lisp','Prolog','Ada','D','Groovy','Visual Basic','Scratch','GDScript','Racket','Elm','WebAssembly','Verilog','VHDL','GLSL','HLSL','CUDA','OpenCL'];
function localJson(file){return JSON.parse(fs.readFileSync(path.join(process.cwd(),'public','data',file),'utf8'))}
function parseLinguist(yaml){const out=[];for(const line of yaml.split(/\r?\n/)){if(/^\S[^:#]*:\s*$/.test(line)){let n=line.slice(0,line.lastIndexOf(':')).trim().replace(/^['"]|['"]$/g,'');if(n&&n.length<90&&!out.includes(n))out.push(n)}}return out.sort((a,b)=>a.localeCompare(b))}
module.exports=async(req,res)=>{const type=String(req.query?.type||'').toLowerCase();const q=String(req.query?.q||'').trim().toLowerCase().slice(0,100);try{
 if(type==='human-languages'){let rows=localJson('human-languages.json');if(q)rows=rows.filter(x=>[x.name,x.commonName,x.alpha2,x.alpha3].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)));return send(res,200,{type,total:rows.length,items:rows.slice(0,1000),note:'ISO 639 catalog. Search Everywhere can research names beyond the visible slice.'})}
 if(type==='countries'){let rows;try{const d=await getJSON('https://restcountries.com/v3.1/all?fields=name,cca2,cca3,capital,region,subregion,population,area,languages,currencies,flags');rows=d.map(x=>({name:x.name?.common||'',officialName:x.name?.official||'',alpha2:x.cca2,alpha3:x.cca3,capital:(x.capital||[]).join(', '),region:x.region||'',subregion:x.subregion||'',population:x.population||0,area:x.area||0,languages:Object.values(x.languages||{}),currencies:Object.values(x.currencies||{}).map(c=>c.name),flag:x.flags?.svg||x.flags?.png||''})).sort((a,b)=>a.name.localeCompare(b.name))}catch{rows=localJson('countries.json')};if(q)rows=rows.filter(x=>[x.name,x.officialName,x.alpha2,x.alpha3,x.region,x.subregion].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)));return send(res,200,{type,total:rows.length,items:rows.slice(0,500)})}
 if(type==='programming'){let names=fallbackProgramming;let source='bundled fallback';try{const y=await getText('https://raw.githubusercontent.com/github-linguist/linguist/master/lib/linguist/languages.yml');const parsed=parseLinguist(y);if(parsed.length>100){names=parsed;source='GitHub Linguist'}}catch{};if(q)names=names.filter(n=>n.toLowerCase().includes(q));return send(res,200,{type,total:names.length,source,items:names.slice(0,1200).map(name=>({name}))})}
 return send(res,400,{error:'Unknown catalog type.'},'no-store');
}catch(e){return send(res,500,{error:'Catalog unavailable.',detail:String(e.message||e)},'no-store')}};
