const store=require('../store');
function send(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','s-maxage=180, stale-while-revalidate=900');res.end(JSON.stringify(data))}
async function getJSON(url,ms=7000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'WebsiteOfBabel/10.0 (open-source research index)'}});if(!r.ok)throw new Error(String(r.status));return await r.json()}finally{clearTimeout(t)}}
function text(s=''){return String(s).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().slice(0,800)}
module.exports=async(req,res)=>{
  const q=String(req.query?.q||'').trim().slice(0,180);if(!q)return send(res,400,{error:'Missing research query.'});
  const ip=(req.headers['x-forwarded-for']||'anonymous').split(',')[0].trim();if(!(await store.rateLimit(`research:${ip}`,40)))return send(res,429,{error:'Too many research requests. Try again shortly.'});
  const enc=encodeURIComponent(q),out=[],media=[],files=[],notes=[];
  const jobs=[
    getJSON(`https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch=${enc}&gsrlimit=8&prop=pageimages%7Cextracts&piprop=thumbnail&pithumbsize=640&exintro=1&explaintext=1&format=json&origin=*`).then(d=>{for(const x of Object.values(d.query?.pages||{}).slice(0,8)){const url=`https://en.wikipedia.org/wiki/${encodeURIComponent(x.title.replace(/ /g,'_'))}`;out.push({source:'Wikipedia',kind:'Reference',title:x.title,url,snippet:text(x.extract||''),image:x.thumbnail?.source||null});if(x.thumbnail?.source)media.push({type:'image',source:'Wikipedia',title:x.title,url:x.thumbnail.source,link:url})}}).catch(()=>notes.push('Wikipedia unavailable')),
    getJSON(`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${enc}&gsrnamespace=6&gsrlimit=10&prop=imageinfo&iiprop=url%7Cextmetadata&iiurlwidth=900&format=json&origin=*`).then(d=>{for(const x of Object.values(d.query?.pages||{}).slice(0,10)){const ii=x.imageinfo?.[0];if(!ii)continue;const title=(ii.extmetadata?.ObjectName?.value||x.title||'Wikimedia Commons image').replace(/^File:/,'');media.push({type:'image',source:'Wikimedia Commons',title:text(title),url:ii.thumburl||ii.url,link:ii.descriptionurl||ii.url})}}).catch(()=>notes.push('Wikimedia Commons unavailable')),
    getJSON(`https://api.openalex.org/works?search=${enc}&per-page=8`).then(d=>{for(const x of (d.results||[]))out.push({source:'OpenAlex',kind:'Scholarship',title:x.display_name||'Untitled work',url:x.doi||x.primary_location?.landing_page_url||x.id,snippet:[x.publication_year,x.primary_location?.source?.display_name,x.cited_by_count!=null?`${x.cited_by_count} citations`:null].filter(Boolean).join(' · '),year:x.publication_year||null})}).catch(()=>notes.push('OpenAlex unavailable')),
    getJSON(`https://archive.org/advancedsearch.php?q=${enc}&fl[]=identifier&fl[]=title&fl[]=description&fl[]=year&fl[]=mediatype&rows=12&page=1&output=json`).then(d=>{for(const x of (d.response?.docs||[])){const url=`https://archive.org/details/${encodeURIComponent(x.identifier)}`;out.push({source:'Internet Archive',kind:'Archive',title:x.title||x.identifier,url,snippet:text(Array.isArray(x.description)?x.description[0]:x.description||''),year:x.year||null});files.push({source:'Internet Archive',title:x.title||x.identifier,identifier:x.identifier,mediatype:x.mediatype||'item',year:x.year||null,url,embed:`https://archive.org/embed/${encodeURIComponent(x.identifier)}`})}}).catch(()=>notes.push('Internet Archive unavailable')),
    getJSON(`https://archive.org/advancedsearch.php?q=(${enc})%20AND%20mediatype%3Amovies&fl[]=identifier&fl[]=title&fl[]=description&fl[]=year&rows=6&page=1&output=json`).then(d=>{for(const x of (d.response?.docs||[])){media.push({type:'archive-video',source:'Internet Archive',title:x.title||x.identifier,url:`https://archive.org/embed/${encodeURIComponent(x.identifier)}`,link:`https://archive.org/details/${encodeURIComponent(x.identifier)}`,thumbnail:`https://archive.org/download/${encodeURIComponent(x.identifier)}/__ia_thumb.jpg`,year:x.year||null})}}).catch(()=>notes.push('Internet Archive video search unavailable')),
    getJSON(`https://hn.algolia.com/api/v1/search?query=${enc}&tags=story&hitsPerPage=6`).then(d=>{for(const x of (d.hits||[]))out.push({source:'Hacker News',kind:'Discussion signal',title:x.title||x.story_title||'Discussion',url:x.url||`https://news.ycombinator.com/item?id=${x.objectID}`,snippet:[x.points!=null?`${x.points} points`:null,x.num_comments!=null?`${x.num_comments} comments`:null].filter(Boolean).join(' · ')})}).catch(()=>notes.push('Hacker News unavailable'))
  ];
  const torEndpoint=String(process.env.BABEL_TOR_RESEARCH_ENDPOINT||'').trim();
  if(torEndpoint){try{const u=new URL(torEndpoint);if(u.protocol==='https:'){u.searchParams.set('q',q);jobs.push((async()=>{const c=new AbortController();const t=setTimeout(()=>c.abort(),7000);try{const headers={'User-Agent':'WebsiteOfBabel/10.0'};if(process.env.BABEL_TOR_RESEARCH_TOKEN)headers.Authorization=`Bearer ${process.env.BABEL_TOR_RESEARCH_TOKEN}`;const r=await fetch(u,{signal:c.signal,headers});if(!r.ok)throw new Error(String(r.status));const d=await r.json();for(const x of (d.results||[]).slice(0,8))out.push({source:'Configured hidden-web adapter',kind:'Hidden-web index',title:String(x.title||'Indexed result').slice(0,240),url:String(x.url||'').slice(0,1500),snippet:text(x.snippet||x.description||'')})}finally{clearTimeout(t)}})().catch(()=>notes.push('Configured hidden-web adapter unavailable')))}else notes.push('Hidden-web adapter ignored because it is not HTTPS')}catch{notes.push('Hidden-web adapter configuration is invalid')}}
  await Promise.allSettled(jobs);
  const seen=new Set();const sources=out.filter(x=>{const k=x.url||x.title;if(!k||seen.has(k))return false;seen.add(k);return true}).slice(0,50);
  const mseen=new Set();const mediaClean=media.filter(x=>{const k=x.url;if(!k||mseen.has(k))return false;mseen.add(k);return true}).slice(0,24);
  const fseen=new Set();const filesClean=files.filter(x=>{const k=x.url;if(!k||fseen.has(k))return false;fseen.add(k);return true}).slice(0,24);
  return send(res,200,{query:q,sources,media:mediaClean,files:filesClean,notes,generatedAt:new Date().toISOString(),message:sources.length?'Live public-source records normalized into Babel. Nothing you search here is permanently published.':'No live sources were reachable.'});
};
