const dns=require('dns').promises;
const net=require('net');
const store=require('../store');
function send(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
function privateIP(ip){if(net.isIP(ip)===4){const a=ip.split('.').map(Number);return a[0]===10||a[0]===127||a[0]===0||(a[0]===169&&a[1]===254)||(a[0]===172&&a[1]>=16&&a[1]<=31)||(a[0]===192&&a[1]===168)||(a[0]>=224)}if(net.isIP(ip)===6){const x=ip.toLowerCase();return x==='::1'||x==='::'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe80:')}return true}
async function validate(raw){let u;try{u=new URL(raw)}catch{throw new Error('Enter a complete http or https URL.')}if(!['http:','https:'].includes(u.protocol))throw new Error('Only http and https URLs are supported.');if(u.hostname.endsWith('.onion'))throw new Error('.onion services require Tor and are not fetched by the Vercel crawler.');if(['localhost','localhost.localdomain'].includes(u.hostname.toLowerCase()))throw new Error('Local addresses are blocked.');if(net.isIP(u.hostname)){if(privateIP(u.hostname))throw new Error('Private and local network addresses are blocked.')}else{const rows=await dns.lookup(u.hostname,{all:true,verbatim:true});if(!rows.length||rows.some(r=>privateIP(r.address)))throw new Error('That host resolves to a private or unsupported address.')}return u}
function cleanText(s=''){return String(s).replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim()}
function attr(tag,name){const m=tag.match(new RegExp(`${name}\\s*=\\s*["']([^"']+)["']`,'i'));return m?m[1]:''}
async function fetchPage(start){let current=await validate(start);for(let i=0;i<4;i++){const c=new AbortController();const t=setTimeout(()=>c.abort(),7000);let r;try{r=await fetch(current,{redirect:'manual',signal:c.signal,headers:{'User-Agent':'WebsiteOfBabelLinkMapper/3.0'}})}finally{clearTimeout(t)}if(r.status>=300&&r.status<400&&r.headers.get('location')){current=await validate(new URL(r.headers.get('location'),current).href);continue}if(!r.ok)throw new Error(`Page returned HTTP ${r.status}.`);const type=r.headers.get('content-type')||'';if(!type.includes('text/html'))throw new Error('The Web Network currently maps HTML pages only.');const buf=await r.arrayBuffer();if(buf.byteLength>1800000)throw new Error('Page is too large to map safely.');return {url:current.href,html:new TextDecoder().decode(buf)}}throw new Error('Too many redirects.')}
module.exports=async(req,res)=>{const raw=String(req.query?.url||'').trim().slice(0,1500);if(!raw)return send(res,400,{error:'Missing URL.'});const ip=(req.headers['x-forwarded-for']||'anonymous').split(',')[0].trim();if(!(await store.rateLimit(`webgraph:${ip}`,20)))return send(res,429,{error:'Too many mapping requests. Try again shortly.'});try{const {url,html}=await fetchPage(raw);const base=new URL(url);const title=cleanText((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||base.hostname).slice(0,180);const desc=cleanText((html.match(/<meta[^>]+(?:name=["']description["'][^>]+content=["']([^"']*)["']|content=["']([^"']*)["'][^>]+name=["']description["'])[^>]*>/i)||[]).slice(1).find(Boolean)||'').slice(0,300);const links=[];const re=/<a\b[^>]*href\s*=\s*["']([^"'#]+)["'][^>]*>/gi;let m;while((m=re.exec(html))&&links.length<450){try{const u=new URL(m[1],base);if(!['http:','https:'].includes(u.protocol))continue;u.hash='';links.push(u.href)}catch{}}const uniq=[...new Set(links)].slice(0,120);const nodes=uniq.map(h=>{const u=new URL(h);return {url:h,host:u.hostname,sameSite:u.hostname===base.hostname}});const hosts=[...new Set(nodes.map(n=>n.host))];return send(res,200,{root:{url,title,description:desc,host:base.hostname},links:nodes,hosts,counts:{links:nodes.length,hosts:hosts.length,internal:nodes.filter(x=>x.sameSite).length,external:nodes.filter(x=>!x.sameSite).length}})}catch(e){return send(res,400,{error:String(e.message||e)})}};
